spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/room_booking
    username: root
    password: ${12345}   # read password from environment variable

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
