spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/room_booking_dev
    username: root
    password: Nada-1417   # <-- CHANGE if your local MySQL root password is different

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
