spring:
  application:
    name: university-room-booking

  datasource:
    url: jdbc:mysql://localhost:3306/room_booking_db
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # (use 'create-drop' in dev if you want to reset db each run)
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

jwt:
  secret: "mysecretkey1234567890"   # we will use this for signing tokens
  expiration: 3600000               # 1 hour in ms
